version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  # AfterInstall:
  #   - location: Scripts/RunResourceTests.sh
  #     timeout: 180
  ApplicationStart:
    - location: Scripts/RunFunctionalTests.sh
      timeout: 300
