version: 0.0
os: linux
files:
  - source: ./src
    destination: /home/ec2-user/Restaurant-Microservice/src
hooks:
  AfterInstall:
    - location: Scripts/RunResourceTests.sh
      timeout: 180
  ApplicationStart:
    - location: Scripts/RunFunctionalTests.sh
      timeout: 3600
