version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: Scripts/RunResourceTests.sh
      timeout: 180
  ApplicationStart:
    - location: Scripts/RunFunctionalTests.sh
      timeout: 300
