version: 0.0
os: linux
files:
  - source: ./src
    destination: /Restaurant-Microservice/
hooks:
  AfterInstall:
    - location: Scripts/RunResourceTests.sh
      timeout: 180
  ApplicationStart:
    - location: Scripts/RunFunctionalTests.sh
      timeout: 3600
